const DEFAULT_ENGINES = [
  {
    id: 'default-duckduckgo',
    name: 'DuckDuckGo',
    source: 'template',
    template: 'https://duckduckgo.com/?q={searchTerms}',
    icon: '',
    contexts: ['text', 'word', 'link', 'image', 'page'],
    resultView: 'tab',
  },
  {
    id: 'default-google',
    name: 'Google',
    source: 'template',
    template: 'https://www.google.com/search?q={searchTerms}',
    icon: '',
    contexts: ['text', 'word', 'link', 'image', 'page'],
    resultView: 'tab',
  },
  {
    id: 'default-bing',
    name: 'Bing',
    source: 'template',
    template: 'https://www.bing.com/search?q={searchTerms}',
    icon: '',
    contexts: ['text', 'word', 'link', 'image', 'page'],
    resultView: 'tab',
  },
  {
    id: 'default-wikipedia',
    name: 'Wikipedia',
    source: 'template',
    template: 'https://en.wikipedia.org/w/index.php?search={searchTerms}',
    icon: '',
    contexts: ['text', 'word', 'link', 'image', 'page'],
    resultView: 'tab',
  },
];
